apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  annotations:
    backstage.io/techdocs-ref: dir:..
    coe/domain: DomainTemplate
    coe/domain-prefix: DomainPrefixTemplate
    coe/k8s-namespace: K8sNamespaceTemplate
  tags:
    - dotnet
spec:
  type: solution
  lifecycle: production
  owner: ${{values.owner}}
  system: ${{values.system_name}}
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: ${{values.app_name + "-solution-data"}}
spec:
  targets:
    - /src/EntrypointFullNamespace/catalog-info.yaml