apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-dotNet-app-template
  title: .Net App Template - WALBER 2
  description: Crie um novo projeto .Net
  tags:
    - dotnet
spec:
  owner: Junto Seguros
  type: service
  parameters:
    - title: Provide some simple information
      required:
        - app_name
        - owner
      properties:
        app_name:
          title: Nome
          type: string
          description: Nome do componente
          ui:field: EntityNamePicker
        description:
          title: Descrição
          type: string
          description: Descrição
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - User
          defaultValue: github/${{identity.githubLogin}}

    - title: Provide some simple information
      required:
        - bar
      properties:
        jira_proj:
          title: Projeto do jira
          type: string
          description: Pergunta 1
        bar:
          title: Bar Title
          type: string
          description: Pergunta 1 com regex
          pattern: '^[a-zA-Z0-9]{3,50}$'

    - title: Provide some simple information
      required:
        - db_created
      properties:

        db_created:
          title: O banco de dados foi criado?
          type: string
          description: O banco de dados foi criado?
          enum:
            - Y
            - N
          enumNames:
            - 'SIM'
            - 'NÃO'

        connection_string:
          title: As connections string foram definidas? (Se houver)
          type: string
          description: As connections string foram definidas? (Se houver)
          enum:
            - Y
            - N
          enumNames:
            - 'SIM'
            - 'NÃO'

        solution_renomeado:
          title: A solution e projetos foram renomeados?
          type: string
          description: A solution e projetos foram renomeados?
          enum:
            - Y
            - N
          enumNames:
            - 'SIM'
            - 'NÃO'

        teste_cobertura:
          title: Os testes de cobertura estão em 80%?
          type: string
          description: Os testes de cobertura estão em 80%?
          enum:
            - Y
            - N
          enumNames:
            - 'SIM'
            - 'NÃO'

        master_branch:
          title: A branch master já está configurada com os padrões e boas práticas de bloqueios e aprovações?
          type: string
          description: A branch master já está configurada com os padrões e boas práticas de bloqueios e aprovações?
          enum:
            - Y
            - N
          enumNames:
            - 'SIM'
            - 'NÃO'

        endpoint_requisitado:
          title: O endpoint será requisitado externamente?
          type: string
          description: O endpoint será requisitado externamente?
          enum:
            - Y
            - N
          enumNames:
            - 'SIM'
            - 'NÃO'

        repo_criado:
          title: Os repositórios foram criados?
          type: string
          description: Os repositórios foram criados?
          enum:
            - Y
            - N
          enumNames:
            - 'SIM'
            - 'NÃO'


  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: .
        copyWithoutRender:
          - .github/workflows/*
        values:
          app_name: ${{ parameters.app_name }}
          description: ${{ parameters.description }}
          repoUrl: 'github.com?repo=${{ parameters.app_name }}&owner=headllama'
          jira_proj: ${{ parameters.jira_proj }}
          owner: ${{ parameters.owner }}

    - id: Rename
      name: Rename solution and project
      action: fs:rename
      input:
        files:
          - from: ./cataloginfo/catalog-info.yaml
            to: ./cataloginfo/catalog-info-${{ parameters.app_name }}.yaml

    - id: Pr_catalog-info
      name: PR do catalog-info
      action: publish:github:pull-request
      input:
        repoUrl: 'github.com?repo=backstage-catalog&owner=GitJMSeguradora'
        targetBranchName: master
        branchName: catalog-${{ parameters.app_name }}
        update: true
        commitMessage: "Adicionando catalog-info para ${{ parameters.app_name }}"
        description: exemplo
        title: "Adicionando catalog-info para ${{ parameters.app_name }}"
        sourcePath: ./cataloginfo

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.app_name }}
        repoUrl: 'github.com?repo=${{ parameters.app_name }}&owner=headllama'
        repoVisibility: 'private'
        sourcePath: ./skeleton

    # - id: register
    #   name: Register
    #   action: catalog:register
    #   input:
    #     repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
    #     catalogInfoPath: "./cataloginfo/catalog-info-${{ parameters.app_name }}.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
