apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: teste-devops
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: coe-tech
    backstage.io/kubernetes-namespace: backstage-ms
    github.com/project-slug: ${{"coe-tech/" + values.app_name}}
    gitlab.com/project-slug: ${{"backstage-apis/" + values.app_name}}
    sonarqube.org/project-key: ${{values.app_name}}
  tags:
      - backend
      - node
      - microservice
  links:
    - url: https://frontreact.rfp.sysmap.dev
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner}}
  system: ${{values.system_name}}
  consumesApis: []
