apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: teste-devops
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: rfp-vivo-2023
  tags:
      - backend
      - node
      - microservice
  links:
    - url: https://frontreact.rfp.sysmap.dev
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: production
  dependsOn: []
  providesApis: []
  apiConsumedBy: []
