apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: headllama/${{ parameters.app_name }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}