apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name + "-api"}}
  tags:
    - dotnet
  links:
    - url: https://${{values.app_name}}.rfp.sysmap.dev
      title: WebApi

spec:
  type: service
  subcomponentOf: ${{values.app_name}}
  lifecycle: production
  owner: ${{values.owner}}
  system: ${{values.system_name}}
  providesApis:
    - ${{values.app_name + "-api"}}