apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: ${{"coe-tech/" + values.app_name}}
    backstage.io/kubernetes-namespace: dice-space
    github.com/project-slug: ${{"coe-tech/" + values.app_name}}
    sonarqube.org/project-key: ${{values.app_name}}
  tags:
      - frontend
      - react
  links:
    - url: https://frontreact.rfp.sysmap.dev
      title: WebApp
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: production
  owner: ${{values.owner}}
  system: ${{values.system_name}}
  consumesApis: []
