apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: coe-tech
    backstage.io/kubernetes-namespace: backstage-ms
    github.com/project-slug: ${{"coe-tech/" + values.app_name}}
    gitlab.com/project-slug: ${{"backstage-apis/" + values.app_name}}
    sonarqube.org/project-key: ${{values.app_name}}
    grafana/dashboard-selector: prometheus-mixin
    grafana/overview-dashboard: 'http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local/d/200ac8fdbfbb74b39aff88118e4d1c2c/kubernetes-compute-resources-node-pods?orgId=1&refresh=10s'
  tags:
      - frontend
      - react
  links:
    - url: https://frontreact.rfp.sysmap.dev
      title: WebApp
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner}}
  system: ${{values.system_name}}
  consumesApis: []
