apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: rfp-vivo-2023
  tags:
      - frontend
      - react
  links:
    - url: https://frontreact.rfp.sysmap.dev
      title: WebApp
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: production
  owner: ${{values.owner}}
  system: ${{values.system_name}}
  consumesApis: []
