site_name: 'RFP Portal Web'
system_name: 'rfp-system'
repo_url: https://gitlab.coe.sysmap.com.br/rfp-vivo-2023/rfp-portal-admin
edit_uri: edit/master/docs

plugins:
  - techdocs-core

nav:
  - Introduction: index.md
