variables:
  PROJETO: ${{values.app_name}}  
  NAMESPACE: ${{values.k8s_namespace}}

# repos
  REGISTRY: "registry.coe.sysmap.com.br/rfp-vivo-2023"

  HELM_CONTAINER: "alpine/helm:latest"

  KUBECONFIG_FILE: ${{"$" + values.k8s_cluster}}

stages:
  - helm-deploy

helm-deploy:
  stage: helm-deploy
  image: 
    name: $HELM_CONTAINER
    entrypoint: [""]
  before_script:
    - export KUBECONFIG=${KUBECONFIG_FILE}  
  script:
    - helm upgrade --install $PROJETO -n $NAMESPACE helm/ --create-namespace --dry-run
