apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  annotations:
    backstage.io/kubernetes-id: rfp-vivo-2023
  tags:
    - recommended
    - coe-arq
    - resources
    - devops
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner}}
  system: ${{values.system_name}}
  dependsOn: []
  providesApis: []
  apiConsumedBy: []
